// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9B7lprXSmZk1r8oWpar_32tPayxiZqLg',
    appId: '1:606792454338:web:e9b4d5810b8c57884dab5b',
    messagingSenderId: '606792454338',
    projectId: 'fir-authentication-783dc',
    authDomain: 'fir-authentication-783dc.firebaseapp.com',
    storageBucket: 'fir-authentication-783dc.firebasestorage.app',
    measurementId: 'G-KVTPF1F18N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVt9vupALYMM93_xP8wOwYB4KHXoeC2YU',
    appId: '1:606792454338:android:299ec116b50a348e4dab5b',
    messagingSenderId: '606792454338',
    projectId: 'fir-authentication-783dc',
    storageBucket: 'fir-authentication-783dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1iyiQ6MDIWGRgZ_sUCIRF66wtjMyfN4',
    appId: '1:606792454338:ios:a376b6ae942977f64dab5b',
    messagingSenderId: '606792454338',
    projectId: 'fir-authentication-783dc',
    storageBucket: 'fir-authentication-783dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1iyiQ6MDIWGRgZ_sUCIRF66wtjMyfN4',
    appId: '1:606792454338:ios:a376b6ae942977f64dab5b',
    messagingSenderId: '606792454338',
    projectId: 'fir-authentication-783dc',
    storageBucket: 'fir-authentication-783dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9B7lprXSmZk1r8oWpar_32tPayxiZqLg',
    appId: '1:606792454338:web:4b9399c2594f97684dab5b',
    messagingSenderId: '606792454338',
    projectId: 'fir-authentication-783dc',
    authDomain: 'fir-authentication-783dc.firebaseapp.com',
    storageBucket: 'fir-authentication-783dc.firebasestorage.app',
    measurementId: 'G-7CKZLF9KXH',
  );
}
